//COPIED AND REFORMATTED FROM ext/filterblade-public-assets/base_types.json
export const BASE_TYPE_MAP = {
    "Daggers": [
        "Glass Shank",
        "Skinning Knife",
        "Stiletto",
        "Flaying Knife",
        "Hollowpoint Dagger",
        "Prong Dagger",
        "Poignard",
        "Pressurised Dagger",
        "Trisula",
        "Gutting Knife",
        "Ambusher",
        "Pneumatic Dagger",
        "Sai"
    ],
    "Fishing Rods": ["Fishing Rod"],
    "Sceptres": [
        "Driftwood Sceptre",
        "Darkwood Sceptre",
        "Bronze Sceptre",
        "Quartz Sceptre",
        "Iron Sceptre",
        "Ochre Sceptre",
        "Ritual Sceptre",
        "Oscillating Sceptre",
        "Shadow Sceptre",
        "Grinning Fetish",
        "Horned Sceptre",
        "Sekhem",
        "Crystal Sceptre",
        "Lead Sceptre",
        "Blood Sceptre",
        "Royal Sceptre",
        "Stabilising Sceptre",
        "Abyssal Sceptre",
        "Stag Sceptre",
        "Karui Sceptre",
        "Tyrant's Sekhem",
        "Opal Sceptre",
        "Platinum Sceptre",
        "Vaal Sceptre",
        "Carnal Sceptre",
        "Void Sceptre",
        "Alternating Sceptre",
        "Sambar Sceptre"
    ],
    "Abyss Jewels": [
        "Ghastly Eye Jewel",
        "Hypnotic Eye Jewel",
        "Murderous Eye Jewel",
        "Searching Eye Jewel"
    ],
    "Atlas Upgrade Items": [
        "Ceremonial Voidstone",
        "Decayed Voidstone",
        "Grasping Voidstone",
        "Omniscient Voidstone"
    ],
    "Utility Flasks": [
        "Quicksilver Flask",
        "Bismuth Flask",
        "Amethyst Flask",
        "Ruby Flask",
        "Sapphire Flask",
        "Topaz Flask",
        "Gold Flask",
        "Aquamarine Flask",
        "Corundum Flask",
        "Diamond Flask",
        "Granite Flask",
        "Jade Flask",
        "Quartz Flask",
        "Sulphur Flask",
        "Basalt Flask",
        "Iron Flask",
        "Silver Flask",
        "Stibnite Flask"
    ],
    "Delve Stackable Socketable Currency": [
        "Potent Chaotic Resonator",
        "Powerful Chaotic Resonator",
        "Prime Chaotic Resonator",
        "Primitive Chaotic Resonator"
    ],
    "Maps": [
        "Abomination Map",
        "Academy Map",
        "Acid Caverns Map",
        "Alleyways Map",
        "Ancient City Map",
        "Arachnid Nest Map",
        "Arachnid Tomb Map",
        "Arcade Map",
        "Arena Map",
        "Arid Lake Map",
        "Armoury Map",
        "Arsenal Map",
        "Ashen Wood Map",
        "Atoll Map",
        "Barrows Map",
        "Basilica Map",
        "Bazaar Map",
        "Beach Map",
        "Belfry Map",
        "Bog Map",
        "Bone Crypt Map",
        "Bramble Valley Map",
        "Burial Chambers Map",
        "Cage Map",
        "Caldera Map",
        "Canyon Map",
        "Carcass Map",
        "Castle Ruins Map",
        "Cells Map",
        "Cemetery Map",
        "Channel Map",
        "Chateau Map",
        "Citadel Map",
        "City Square Map",
        "Cold River Map",
        "Colonnade Map",
        "Colosseum Map",
        "Conservatory Map",
        "Coral Ruins Map",
        "Core Map",
        "Courthouse Map",
        "Courtyard Map",
        "Coves Map",
        "Crater Map",
        "Crimson Temple Map",
        "Crimson Township Map",
        "Crystal Ore Map",
        "Cursed Crypt Map",
        "Dark Forest Map",
        "Defiled Cathedral Map",
        "Desert Map",
        "Desert Spring Map",
        "Dig Map",
        "Dry Sea Map",
        "Dunes Map",
        "Dungeon Map",
        "Estuary Map",
        "Excavation Map",
        "Factory Map",
        "Fields Map",
        "Flooded Mine Map",
        "Forbidden Woods Map",
        "Forking River Map",
        "Fortress Map",
        "Foundry Map",
        "Frozen Cabins Map",
        "Fungal Hollow Map",
        "Gardens Map",
        "Geode Map",
        "Ghetto Map",
        "Glacier Map",
        "Grave Trough Map",
        "Graveyard Map",
        "Grotto Map",
        "Harbinger Map",
        "Haunted Mansion Map",
        "Iceberg Map",
        "Infested Valley Map",
        "Ivory Temple Map",
        "Jungle Valley Map",
        "Laboratory Map",
        "Lair Map",
        "Lava Chamber Map",
        "Lava Lake Map",
        "Leyline Map",
        "Lighthouse Map",
        "Lookout Map",
        "Malformation Map",
        "Marshes Map",
        "Mausoleum Map",
        "Maze Map",
        "Mesa Map",
        "Mineral Pools Map",
        "Moon Temple Map",
        "Mud Geyser Map",
        "Museum Map",
        "Necropolis Map",
        "Orchard Map",
        "Overgrown Ruin Map",
        "Overgrown Shrine Map",
        "Palace Map",
        "Park Map",
        "Pen Map",
        "Peninsula Map",
        "Phantasmagoria Map",
        "Pier Map",
        "Pit Map",
        "Plateau Map",
        "Plaza Map",
        "Port Map",
        "Precinct Map",
        "Primordial Blocks Map",
        "Primordial Pool Map",
        "Promenade Map",
        "Racecourse Map",
        "Ramparts Map",
        "Reef Map",
        "Relic Chambers Map",
        "Residence Map",
        "Sanctuary Map",
        "Scriptorium Map",
        "Sepulchre Map",
        "Shipyard Map",
        "Shore Map",
        "Shrine Map",
        "Siege Map",
        "Silo Map",
        "Spider Forest Map",
        "Spider Lair Map",
        "Stagnation Map",
        "Strand Map",
        "Sulphur Vents Map",
        "Summit Map",
        "Sunken City Map",
        "Synthesised Map",
        "Temple Map",
        "Terrace Map",
        "Thicket Map",
        "Tower Map",
        "Toxic Sewer Map",
        "Tropical Island Map",
        "Underground River Map",
        "Underground Sea Map",
        "Vaal Pyramid Map",
        "Vaal Temple Map",
        "Vault Map",
        "Villa Map",
        "Volcano Map",
        "Waste Pool Map",
        "Wasteland Map",
        "Waterways Map",
        "Wharf Map",
        "Ziggurat Map",
        "Forge of the Phoenix Map",
        "Lair of the Hydra Map",
        "Maze of the Minotaur Map",
        "Pit of the Chimera Map"
    ],
    "Labyrinth Trinkets": [
        "Bane of the Loyal",
        "Cogs of Disruption",
        "Cube Of Absorption",
        "Heart of the Gargoyle",
        "Orb of Elemental Dispersion",
        "Portal Shredder",
        "Rod of Detonation",
        "Sand of Eternity"
    ],
    "Gloves": [
        "Iron Gauntlets",
        "Rawhide Gloves",
        "Wool Gloves",
        "Fishscale Gauntlets",
        "Wrapped Mitts",
        "Chain Gloves",
        "Goathide Gloves",
        "Gauche Gloves",
        "Leyline Gloves",
        "Taxing Gauntlets",
        "Plated Gauntlets",
        "Velvet Gloves",
        "Ironscale Gauntlets",
        "Strapped Mitts",
        "Ringmail Gloves",
        "Deerskin Gloves",
        "Bronze Gauntlets",
        "Runic Gloves",
        "Silk Gloves",
        "Bronzescale Gauntlets",
        "Clasped Mitts",
        "Mesh Gloves",
        "Nubuck Gloves",
        "Steel Gauntlets",
        "Embroidered Gloves",
        "Steelscale Gauntlets",
        "Trapper Mitts",
        "Riveted Gloves",
        "Eelskin Gloves",
        "Antique Gauntlets",
        "Aetherwind Gloves",
        "Gruelling Gauntlets",
        "Southswing Gloves",
        "Satin Gloves",
        "Serpentscale Gauntlets",
        "Zealot Gloves",
        "Ambush Mitts",
        "Sharkskin Gloves",
        "Ancient Gauntlets",
        "Samite Gloves",
        "Runic Gages",
        "Wyrmscale Gauntlets",
        "Carnal Mitts",
        "Soldier Gloves",
        "Goliath Gauntlets",
        "Shagreen Gloves",
        "Conjurer Gloves",
        "Legion Gloves",
        "Assassin's Mitts",
        "Hydrascale Gauntlets",
        "Arcanist Gloves",
        "Stealth Gloves",
        "Vaal Gauntlets",
        "Crusader Gloves",
        "Dragonscale Gauntlets",
        "Murder Mitts",
        "Runic Gauntlets",
        "Sorcerer Gloves",
        "Titan Gauntlets",
        "Apothecary's Gloves",
        "Debilitation Gauntlets",
        "Fingerless Silk Gloves",
        "Gripped Gloves",
        "Nexus Gloves",
        "Sinistral Gloves",
        "Slink Gloves",
        "Spiked Gloves"
    ],
    "Incursion Items": [
        "Flashpowder Keg",
        "Stone of Passage"
    ],
    "Staves": [
        "Gnarled Branch",
        "Primitive Staff",
        "Long Staff",
        "Royal Staff",
        "Transformer Staff",
        "Crescent Staff",
        "Woodful Staff",
        "Quarterstaff",
        "Reciprocation Staff",
        "Highborn Staff",
        "Moon Staff",
        "Primordial Staff",
        "Lathi",
        "Imperial Staff",
        "Battery Staff",
        "Eclipse Staff"
    ],
    "Bows": [
        "Crude Bow",
        "Short Bow",
        "Long Bow",
        "Composite Bow",
        "Recurve Bow",
        "Bone Bow",
        "Royal Bow",
        "Hedron Bow",
        "Death Bow",
        "Grove Bow",
        "Reflex Bow",
        "Decurve Bow",
        "Compound Bow",
        "Sniper Bow",
        "Ivory Bow",
        "Foundry Bow",
        "Highborn Bow",
        "Decimation Bow",
        "Thicket Bow",
        "Steelwood Bow",
        "Citadel Bow",
        "Ranger Bow",
        "Assassin Bow",
        "Spine Bow",
        "Imperial Bow",
        "Harbinger Bow",
        "Solarine Bow",
        "Maraketh Bow"
    ],
    "Rings": [
        "Breach Ring",
        "Ring",
        "Shadowed Ring",
        "Iron Ring",
        "Coral Ring",
        "Paua Ring",
        "Sapphire Ring",
        "Topaz Ring",
        "Ruby Ring",
        "Gold Ring",
        "Two-Stone Ring",
        "Cogwork Ring",
        "Composite Ring",
        "Diamond Ring",
        "Dusk Ring",
        "Geodesic Ring",
        "Gloam Ring",
        "Helical Ring",
        "Manifold Ring",
        "Moonstone Ring",
        "Penumbra Ring",
        "Ratcheting Ring",
        "Tenebrous Ring",
        "Bone Ring",
        "Prismatic Ring",
        "Amethyst Ring",
        "Unset Ring",
        "Iolite Ring",
        "Opal Ring",
        "Steel Ring",
        "Cerulean Ring",
        "Vermillion Ring"
    ],
    "One Hand Swords": [
        "Rusted Sword",
        "Copper Sword",
        "Sabre",
        "Broad Sword",
        "War Sword",
        "Ancient Sword",
        "Elegant Sword",
        "Fickle Spiritblade",
        "Dusk Blade",
        "Hook Sword",
        "Variscite Blade",
        "Cutlass",
        "Baselard",
        "Battle Sword",
        "Elder Sword",
        "Capricious Spiritblade",
        "Graceful Sword",
        "Twilight Blade",
        "Grappler",
        "Gemstone Sword",
        "Corsair Sword",
        "Gladius",
        "Legion Sword",
        "Vaal Blade",
        "Eternal Sword",
        "Midnight Blade",
        "Anarchic Spiritblade",
        "Tiger Hook"
    ],
    "Incubators": [
        "Abyssal Incubator",
        "Blighted Incubator",
        "Cartographer's Incubator",
        "Celestial Armoursmith's Incubator",
        "Celestial Blacksmith's Incubator",
        "Celestial Jeweller's Incubator",
        "Challenging Incubator",
        "Diviner's Incubator",
        "Enchanted Incubator",
        "Fine Incubator",
        "Foreboding Incubator",
        "Fossilised Incubator",
        "Fragmented Incubator",
        "Gemcutter's Incubator",
        "Geomancer's Incubator",
        "Infused Incubator",
        "Kalguuran Incubator",
        "Maddening Incubator",
        "Mysterious Incubator",
        "Obscured Incubator",
        "Ornate Incubator",
        "Otherworldly Incubator",
        "Primal Incubator",
        "Singular Incubator",
        "Skittering Incubator",
        "Thaumaturge's Incubator",
        "Whispering Incubator"
    ],
    "Memories": [
        "Alva's Memory",
        "Einhar's Memory",
        "Kirac's Memory",
        "Niko's Memory"
    ],
    "Shields": [
        "Splintered Tower Shield",
        "Goathide Buckler",
        "Twig Spirit Shield",
        "Corroded Tower Shield",
        "Rotted Round Shield",
        "Spiked Bundle",
        "Plank Kite Shield",
        "Pine Buckler",
        "Yew Spirit Shield",
        "Rawhide Tower Shield",
        "Driftwood Spiked Shield",
        "Fir Round Shield",
        "Linden Kite Shield",
        "Bone Spirit Shield",
        "Painted Buckler",
        "Cedar Tower Shield",
        "Alloyed Spiked Shield",
        "Reinforced Kite Shield",
        "Studded Round Shield",
        "Hammered Buckler",
        "Tarnished Spirit Shield",
        "Copper Tower Shield",
        "Burnished Spiked Shield",
        "Layered Kite Shield",
        "Scarlet Round Shield",
        "Jingling Spirit Shield",
        "War Buckler",
        "Endothermic Buckler",
        "Exhausting Spirit Shield",
        "Exothermic Tower Shield",
        "Reinforced Tower Shield",
        "Brass Spirit Shield",
        "Ornate Spiked Shield",
        "Splendid Round Shield",
        "Ceremonial Kite Shield",
        "Gilded Buckler",
        "Painted Tower Shield",
        "Walnut Spirit Shield",
        "Oak Buckler",
        "Buckskin Tower Shield",
        "Maple Round Shield",
        "Redwood Spiked Shield",
        "Etched Kite Shield",
        "Ivory Spirit Shield",
        "Enameled Buckler",
        "Mahogany Tower Shield",
        "Ancient Spirit Shield",
        "Compound Spiked Shield",
        "Spiked Round Shield",
        "Corrugated Buckler",
        "Steel Kite Shield",
        "Bronze Tower Shield",
        "Chiming Spirit Shield",
        "Crimson Round Shield",
        "Polished Spiked Shield",
        "Battle Buckler",
        "Laminated Kite Shield",
        "Magmatic Tower Shield",
        "Polar Buckler",
        "Subsuming Spirit Shield",
        "Girded Tower Shield",
        "Thorium Spirit Shield",
        "Baroque Round Shield",
        "Golden Buckler",
        "Sovereign Spiked Shield",
        "Angelic Kite Shield",
        "Crested Tower Shield",
        "Lacewood Spirit Shield",
        "Ironwood Buckler",
        "Alder Spiked Shield",
        "Shagreen Tower Shield",
        "Teak Round Shield",
        "Branded Kite Shield",
        "Fossilised Spirit Shield",
        "Lacquered Buckler",
        "Ebony Tower Shield",
        "Champion Kite Shield",
        "Ezomyte Spiked Shield",
        "Spiny Round Shield",
        "Vaal Spirit Shield",
        "Vaal Buckler",
        "Ezomyte Tower Shield",
        "Harmonic Spirit Shield",
        "Mosaic Kite Shield",
        "Cardinal Round Shield",
        "Crusader Buckler",
        "Mirrored Spiked Shield",
        "Colossal Tower Shield",
        "Archon Kite Shield",
        "Titanium Spirit Shield",
        "Imperial Buckler",
        "Cold-attuned Buckler",
        "Elegant Round Shield",
        "Heat-attuned Tower Shield",
        "Pinnacle Tower Shield",
        "Supreme Spiked Shield",
        "Transfer-attuned Spirit Shield"
    ],
    "Pieces": [
        "Archon Kite Shield Piece",
        "Blunt Arrow Quiver Piece",
        "Callous Mask Piece",
        "Cloth Belt Piece",
        "Imperial Staff Piece",
        "Legion Sword Piece",
        "Vaal Aspect"
    ],
    "Vault Keys": [
        "Ancient Reliquary Key",
        "Archive Reliquary Key",
        "Cosmic Reliquary Key",
        "Decaying Reliquary Key",
        "Forgotten Reliquary Key",
        "Oubliette Reliquary Key",
        "Shiny Reliquary Key",
        "Timeworn Reliquary Key",
        "Visceral Reliquary Key",
        "Voidborn Reliquary Key",
        "Vaal Reliquary Key"
    ],
    "Charms": [
        "Corvine Charm",
        "Lupine Charm",
        "Ursine Charm"
    ],
    "Thrusting One Hand Swords": [
        "Rusted Spike",
        "Whalebone Rapier",
        "Battered Foil",
        "Basket Rapier",
        "Jagged Foil",
        "Antique Rapier",
        "Elegant Foil",
        "Thorn Rapier",
        "Smallsword",
        "Wyrmbone Rapier",
        "Burnished Foil",
        "Estoc",
        "Serrated Foil",
        "Primeval Rapier",
        "Fancy Foil",
        "Apex Rapier",
        "Courtesan Sword",
        "Dragonbone Rapier",
        "Tempered Foil",
        "Pecoraro",
        "Spiraled Foil",
        "Vaal Rapier",
        "Jewelled Foil",
        "Harpy Rapier",
        "Dragoon Sword"
    ],
    "Breachstones": [
        "Esh's Breachstone",
        "Tul's Breachstone",
        "Xoph's Breachstone",
        "Uul-Netol's Breachstone",
        "Chayula's Breachstone",
        "Chayula's Flawless Breachstone",
        "Esh's Flawless Breachstone",
        "Tul's Flawless Breachstone",
        "Uul-Netol's Flawless Breachstone",
        "Xoph's Flawless Breachstone"
    ],
    "Wands": [
        "Driftwood Wand",
        "Goat's Horn",
        "Carved Wand",
        "Quartz Wand",
        "Calling Wand",
        "Spiraled Wand",
        "Assembler Wand",
        "Sage Wand",
        "Pagan Wand",
        "Faun's Horn",
        "Engraved Wand",
        "Crystal Wand",
        "Coiled Wand",
        "Congregator Wand",
        "Convening Wand",
        "Omen Wand",
        "Heathen Wand",
        "Demon's Horn",
        "Imbued Wand",
        "Opal Wand",
        "Tornado Wand",
        "Prophecy Wand",
        "Accumulator Wand",
        "Profane Wand",
        "Convoking Wand"
    ],
    "Embers of the Allflame": [
        "Allflame Ember of Abyss",
        "Allflame Ember of Anarchy",
        "Allflame Ember of Arohongui",
        "Allflame Ember of Artillery Gemlings",
        "Allflame Ember of Beidat",
        "Allflame Ember of Berserking Gemlings",
        "Allflame Ember of Brawling Gemlings",
        "Allflame Ember of Chayula",
        "Allflame Ember of Corpsemage Gemlings",
        "Allflame Ember of Esh",
        "Allflame Ember of Frogs",
        "Allflame Ember of Frostmage Gemlings",
        "Allflame Ember of Ghorr",
        "Allflame Ember of Hinekora",
        "Allflame Ember of K'tash",
        "Allflame Ember of Kitava",
        "Allflame Ember of Manifested Wealth",
        "Allflame Ember of Meatsacks",
        "Allflame Ember of Ngamahu",
        "Allflame Ember of Ramako",
        "Allflame Ember of Rats",
        "Allflame Ember of Rongokurai",
        "Allflame Ember of Sulphite",
        "Allflame Ember of Syndicate Assassins",
        "Allflame Ember of Syndicate Escorts",
        "Allflame Ember of Syndicate Guards",
        "Allflame Ember of Syndicate Researchers",
        "Allflame Ember of Synthetic Fury",
        "Allflame Ember of Tasalio",
        "Allflame Ember of Tawhoa",
        "Allflame Ember of The Black Scythe",
        "Allflame Ember of The Broken Circle",
        "Allflame Ember of The Crusader",
        "Allflame Ember of The Elder",
        "Allflame Ember of The Eternal Legion",
        "Allflame Ember of The Hunter",
        "Allflame Ember of The Karui Legion",
        "Allflame Ember of The Knights of the Sun",
        "Allflame Ember of The Maraketh Legion",
        "Allflame Ember of The Order of the Chalice",
        "Allflame Ember of The Redeemer",
        "Allflame Ember of The Shaper",
        "Allflame Ember of The Templar Legion",
        "Allflame Ember of The Vaal Legion",
        "Allflame Ember of The Warlord",
        "Allflame Ember of Trial Cores",
        "Allflame Ember of Trial Guards",
        "Allflame Ember of Tukohama",
        "Allflame Ember of Tul",
        "Allflame Ember of Untainted Apes",
        "Allflame Ember of Untainted Beasts",
        "Allflame Ember of Untainted Chimerals",
        "Allflame Ember of Untainted Devourers",
        "Allflame Ember of Untainted Maws",
        "Allflame Ember of Untainted Rhoas",
        "Allflame Ember of Untainted Spitters",
        "Allflame Ember of Uul-Netol",
        "Allflame Ember of Valako",
        "Allflame Ember of Wildwood Beasts",
        "Allflame Ember of Wildwood Cultists",
        "Allflame Ember of Wildwood Treants",
        "Allflame Ember of Xoph",
        "Allflame Ember of the False God",
        "Flaring Allflame Ember of Abyss",
        "Flaring Allflame Ember of Breachlords",
        "Flaring Allflame Ember of Kalguurans",
        "Flaring Allflame Ember of Scientists",
        "Flaring Allflame Ember of The First Ones",
        "Flaring Allflame Ember of Wildwood Cultists",
        "Flaring Allflame Ember of the Vaal"
    ],
    "Skill Gems": [
        "Automation",
        "Blade Trap",
        "Call to Arms",
        "Energy Blade",
        "Frozen Legion",
        "Snipe",
        "Vaal Absolution",
        "Vaal Animate Weapon",
        "Vaal Arctic Armour",
        "Vaal Blade Flurry",
        "Vaal Blight",
        "Vaal Burning Arrow",
        "Vaal Caustic Arrow",
        "Vaal Cleave",
        "Vaal Domination",
        "Vaal Double Strike",
        "Vaal Fireball",
        "Vaal Firestorm",
        "Vaal Flicker Strike",
        "Vaal Glacial Hammer",
        "Vaal Ground Slam",
        "Vaal Ice Shot",
        "Vaal Lightning Arrow",
        "Vaal Molten Strike",
        "Vaal Reap",
        "Vaal Rejuvenation Totem",
        "Vaal Smite",
        "Vaal Spark",
        "Vaal Spectral Throw",
        "Vaal Venom Gyre",
        "Vaal Volcanic Fissure",
        "Volcanic Fissure",
        "Vaal Detonate Dead",
        "Vaal Molten Shell",
        "Ancestral Protector",
        "Animate Weapon",
        "Bear Trap",
        "Blight",
        "Blood and Sand",
        "Burning Arrow",
        "Caustic Arrow",
        "Cleave",
        "Cobra Lash",
        "Contagion",
        "Conversion Trap",
        "Dash",
        "Decoy Totem",
        "Detonate Dead",
        "Devouring Totem",
        "Double Strike",
        "Dual Strike",
        "Ethereal Knives",
        "Explosive Trap",
        "Fireball",
        "Flame Wall",
        "Freezing Pulse",
        "Frost Blades",
        "Frost Bomb",
        "Frost Wall",
        "Frostblink",
        "Frostbolt",
        "Galvanic Arrow",
        "Glacial Hammer",
        "Ground Slam",
        "Heavy Strike",
        "Holy Flame Totem",
        "Ice Shot",
        "Kinetic Bolt",
        "Lightning Tendrils",
        "Molten Shell",
        "Molten Strike",
        "Orb of Storms",
        "Perforate",
        "Puncture",
        "Purifying Flame",
        "Raise Zombie",
        "Reckoning",
        "Rejuvenation Totem",
        "Riposte",
        "Rolling Magma",
        "Shield Crush",
        "Shrapnel Ballista",
        "Smite",
        "Spark",
        "Spectral Throw",
        "Split Arrow",
        "Splitting Steel",
        "Steelskin",
        "Stormblast Mine",
        "Summon Holy Relic",
        "Summon Raging Spirit",
        "Vigilant Strike",
        "Viper Strike",
        "War Banner",
        "Detonate Mines",
        "Blink Arrow",
        "Bodyswap",
        "Clarity",
        "Enduring Cry",
        "Flame Dash",
        "Flicker Strike",
        "Intimidating Cry",
        "Leap Slam",
        "Lightning Warp",
        "Mirror Arrow",
        "Portal",
        "Precision",
        "Shield Charge",
        "Siphoning Trap",
        "Smoke Mine",
        "Summon Skeletons",
        "Unearth",
        "Vaal Breach",
        "Vaal Clarity",
        "Vaal Lightning Warp",
        "Vaal Summon Skeletons",
        "Vitality",
        "Whirling Blades",
        "Wither",
        "Withering Step",
        "Absolution",
        "Arc",
        "Barrage",
        "Blade Vortex",
        "Blazing Salvo",
        "Bone Offering",
        "Chain Hook",
        "Creeping Frost",
        "Earthshatter",
        "Elemental Hit",
        "Essence Drain",
        "Exsanguinate",
        "Fire Trap",
        "Flame Surge",
        "Flesh Offering",
        "Ice Nova",
        "Ice Spear",
        "Icicle Mine",
        "Incinerate",
        "Infernal Blow",
        "Lacerate",
        "Lightning Arrow",
        "Lightning Strike",
        "Lightning Trap",
        "Manabond",
        "Poisonous Concoction",
        "Power Siphon",
        "Rain of Arrows",
        "Reave",
        "Scorching Ray",
        "Searing Bond",
        "Shattering Steel",
        "Siege Ballista",
        "Spectral Helix",
        "Spirit Offering",
        "Static Strike",
        "Storm Brand",
        "Storm Burst",
        "Storm Call",
        "Sunder",
        "Sweep",
        "Toxic Rain",
        "Vaal Arc",
        "Vaal Blade Vortex",
        "Vaal Ice Nova",
        "Vaal Lightning Strike",
        "Vaal Lightning Trap",
        "Vaal Power Siphon",
        "Vaal Rain of Arrows",
        "Vaal Reave",
        "Vaal Storm Call",
        "Venom Gyre",
        "Volatile Dead",
        "Voltaxic Burst",
        "Wintertide Brand",
        "Ancestral Cry",
        "Arcane Cloak",
        "Arctic Armour",
        "Blade Blast",
        "Blood Rage",
        "Brand Recall",
        "Cold Snap",
        "Corrupting Fever",
        "Defiance Banner",
        "Desecrate",
        "Ensnaring Arrow",
        "Flesh and Stone",
        "Forbidden Rite",
        "Frenzy",
        "Galvanic Field",
        "Herald of Agony",
        "Herald of Ash",
        "Herald of Ice",
        "Herald of Purity",
        "Herald of Thunder",
        "Righteous Fire",
        "Seismic Cry",
        "Summon Skitterbots",
        "Tempest Shield",
        "Vaal Cold Snap",
        "Vaal Righteous Fire",
        "Wave of Conviction",
        "Alchemist's Mark",
        "Anger",
        "Assassin's Mark",
        "Bane",
        "Battlemage's Cry",
        "Conductivity",
        "Convocation",
        "Despair",
        "Determination",
        "Discipline",
        "Dread Banner",
        "Elemental Weakness",
        "Enfeeble",
        "Flammability",
        "Frostbite",
        "General's Cry",
        "Grace",
        "Haste",
        "Hatred",
        "Infernal Cry",
        "Malevolence",
        "Petrified Blood",
        "Plague Bearer",
        "Poacher's Mark",
        "Pride",
        "Punishment",
        "Purity of Elements",
        "Purity of Fire",
        "Purity of Ice",
        "Purity of Lightning",
        "Rallying Cry",
        "Sniper's Mark",
        "Spellslinger",
        "Temporal Chains",
        "Vaal Discipline",
        "Vaal Grace",
        "Vaal Haste",
        "Vaal Impurity of Fire",
        "Vaal Impurity of Ice",
        "Vaal Impurity of Lightning",
        "Vengeance",
        "Vulnerability",
        "Warlord's Mark",
        "Wrath",
        "Zealotry",
        "Ancestral Warchief",
        "Animate Guardian",
        "Armageddon Brand",
        "Artillery Ballista",
        "Ball Lightning",
        "Blade Flurry",
        "Bladefall",
        "Bladestorm",
        "Blast Rain",
        "Boneshatter",
        "Charged Dash",
        "Consecrated Path",
        "Crackling Lance",
        "Cremation",
        "Cyclone",
        "Dark Pact",
        "Discharge",
        "Divine Ire",
        "Dominating Blow",
        "Earthquake",
        "Explosive Arrow",
        "Explosive Concoction",
        "Eye of Winter",
        "Firestorm",
        "Flameblast",
        "Flamethrower Trap",
        "Glacial Cascade",
        "Hexblast",
        "Ice Crash",
        "Ice Trap",
        "Kinetic Blast",
        "Lancing Steel",
        "Lightning Conduit",
        "Lightning Spire Trap",
        "Penance Brand",
        "Pestilent Strike",
        "Pyroclast Mine",
        "Rage Vortex",
        "Raise Spectre",
        "Reap",
        "Scourge Arrow",
        "Seismic Trap",
        "Shock Nova",
        "Shockwave Totem",
        "Soulrend",
        "Spectral Shield Throw",
        "Storm Rain",
        "Stormbind",
        "Summon Reaper",
        "Tectonic Slam",
        "Tornado Shot",
        "Vaal Ancestral Warchief",
        "Vaal Cyclone",
        "Vaal Earthquake",
        "Vaal Flameblast",
        "Vortex",
        "Wild Strike",
        "Winter Orb",
        "Ambush",
        "Berserk",
        "Destructive Link",
        "Flame Link",
        "Frost Shield",
        "Hydrosphere",
        "Immortal Call",
        "Intuitive Link",
        "Phase Run",
        "Protective Link",
        "Sigil of Power",
        "Soul Link",
        "Summon Carrion Golem",
        "Summon Chaos Golem",
        "Summon Flame Golem",
        "Summon Ice Golem",
        "Summon Lightning Golem",
        "Summon Stone Golem",
        "Temporal Rift",
        "Tornado",
        "Vaal Immortal Call",
        "Vampiric Link",
        "Void Sphere",
        "Arcanist Brand"
    ],
    "Stackable Currency": [
        "Aberrant Fossil",
        "Abrasive Catalyst",
        "Abyssal Delirium Orb",
        "Accelerating Catalyst",
        "Aetheric Fossil",
        "Alchemy Shard",
        "Alteration Shard",
        "Amplifying Power Core",
        "Ancient Orb",
        "Armourer's Scrap",
        "Armoursmith's Delirium Orb",
        "Astragali",
        "Augmenting Power Core",
        "Awakener's Orb",
        "Blacksmith's Delirium Orb",
        "Blacksmith's Whetstone",
        "Blessing of Chayula",
        "Blessing of Esh",
        "Blessing of Tul",
        "Blessing of Uul-Netol",
        "Blessing of Xoph",
        "Blighted Delirium Orb",
        "Bloodstained Fossil",
        "Bound Fossil",
        "Burial Medallion",
        "Cartographer's Delirium Orb",
        "Challenging Delirium Orb",
        "Clear Oil",
        "Corroded Fossil",
        "Crusader's Exalted Orb",
        "Deft Fossil",
        "Dense Fossil",
        "Deregulation Scroll",
        "Diviner's Delirium Orb",
        "Electroshock Scroll",
        "Empty Coffin",
        "Engineer's Orb",
        "Eternal Orb",
        "Exotic Coinage",
        "Faceted Fossil",
        "Facetor's Lens",
        "Fertile Catalyst",
        "Filled Coffin",
        "Fine Delirium Orb",
        "Foreboding Delirium Orb",
        "Fossilised Delirium Orb",
        "Fractured Fossil",
        "Fragmentation Scroll",
        "Fragmented Delirium Orb",
        "Frigid Fossil",
        "Fundamental Fossil",
        "Gilded Fossil",
        "Glyphic Fossil",
        "Haemocombustion Scroll",
        "Harbinger's Orb",
        "Hinekora's Lock",
        "Hollow Fossil",
        "Hunter's Exalted Orb",
        "Imbued Catalyst",
        "Imperial Delirium Orb",
        "Imprint",
        "Imprinted Bestiary Orb",
        "Intrinsic Catalyst",
        "Jagged Fossil",
        "Jeweller's Delirium Orb",
        "Lucent Fossil",
        "Metallic Fossil",
        "Noxious Catalyst",
        "Obscured Delirium Orb",
        "Oil Extractor",
        "Omen of Adrenaline",
        "Omen of Amelioration",
        "Omen of Blanching",
        "Omen of Brilliance",
        "Omen of Connections",
        "Omen of Death's Door",
        "Omen of Death-dancing",
        "Omen of Fortune",
        "Omen of Refreshment",
        "Omen of Return",
        "Omen of the Jeweller",
        "Omen of the Soul Devourer",
        "Orb of Augmentation",
        "Orb of Conflict",
        "Orb of Dominance",
        "Orb of Transmutation",
        "Perfect Fossil",
        "Power Core",
        "Primal Crystallised Lifeforce",
        "Prismatic Catalyst",
        "Prismatic Fossil",
        "Pristine Fossil",
        "Redeemer's Exalted Orb",
        "Reflective Oil",
        "Ritual Splinter",
        "Ritual Vessel",
        "Sacred Crystallised Lifeforce",
        "Sanctified Fossil",
        "Scorched Fossil",
        "Scrap Metal",
        "Scroll Fragment",
        "Scroll of Wisdom",
        "Serrated Fossil",
        "Shuddering Fossil",
        "Simulacrum Splinter",
        "Singular Delirium Orb",
        "Skittering Delirium Orb",
        "Specularity Scroll",
        "Splinter of Chayula",
        "Splinter of Esh",
        "Splinter of Tul",
        "Splinter of Uul-Netol",
        "Splinter of Xoph",
        "Tailoring Orb",
        "Tainted Armourer's Scrap",
        "Tainted Blacksmith's Whetstone",
        "Tainted Catalyst",
        "Tainted Oil",
        "Tangled Fossil",
        "Tempering Catalyst",
        "Tempering Orb",
        "Thaumaturge's Delirium Orb",
        "Time-light Scroll",
        "Timeless Delirium Orb",
        "Timeless Eternal Empire Splinter",
        "Timeless Karui Splinter",
        "Timeless Maraketh Splinter",
        "Timeless Templar Splinter",
        "Timeless Vaal Splinter",
        "Transforming Power Core",
        "Transmutation Shard",
        "Turbulent Catalyst",
        "Unstable Catalyst",
        "Valdo's Puzzle Box",
        "Vivid Crystallised Lifeforce",
        "Warlord's Exalted Orb",
        "Whispering Delirium Orb",
        "Whispering Essence of Contempt",
        "Whispering Essence of Greed",
        "Whispering Essence of Hatred",
        "Whispering Essence of Woe",
        "Wild Crystallised Lifeforce",
        "Chromatic Orb",
        "Glassblower's Bauble",
        "Orb of Alchemy",
        "Orb of Alteration",
        "Orb of Chance",
        "Orb of Regret",
        "Portal Scroll",
        "Tainted Chromatic Orb",
        "Tainted Mythic Orb",
        "Chaos Shard",
        "Engineer's Shard",
        "Jeweller's Orb",
        "Orb of Fusing",
        "Tainted Jeweller's Orb",
        "Muttering Essence of Anger",
        "Muttering Essence of Contempt",
        "Muttering Essence of Fear",
        "Muttering Essence of Greed",
        "Muttering Essence of Hatred",
        "Muttering Essence of Sorrow",
        "Muttering Essence of Torment",
        "Muttering Essence of Woe",
        "Sepia Oil",
        "Chaos Orb",
        "Gemcutter's Prism",
        "Orb of Scouring",
        "Regal Orb",
        "Regal Shard",
        "Tainted Chaos Orb",
        "Vaal Orb",
        "Bestiary Orb",
        "Amber Oil",
        "Binding Shard",
        "Orb of Binding",
        "Remnant of Corruption",
        "Weeping Essence of Anger",
        "Weeping Essence of Contempt",
        "Weeping Essence of Doubt",
        "Weeping Essence of Fear",
        "Weeping Essence of Greed",
        "Weeping Essence of Hatred",
        "Weeping Essence of Rage",
        "Weeping Essence of Sorrow",
        "Weeping Essence of Suffering",
        "Weeping Essence of Torment",
        "Weeping Essence of Woe",
        "Weeping Essence of Wrath",
        "Verdant Oil",
        "Ancient Shard",
        "Annulment Shard",
        "Blessed Orb",
        "Divine Orb",
        "Exalted Orb",
        "Exalted Shard",
        "Mirror Shard",
        "Mirror of Kalandra",
        "Orb of Annulment",
        "Sacred Orb",
        "Tainted Exalted Orb",
        "Teal Oil",
        "Enkindling Orb",
        "Instilling Orb",
        "Wailing Essence of Anger",
        "Wailing Essence of Anguish",
        "Wailing Essence of Contempt",
        "Wailing Essence of Doubt",
        "Wailing Essence of Fear",
        "Wailing Essence of Greed",
        "Wailing Essence of Hatred",
        "Wailing Essence of Loathing",
        "Wailing Essence of Rage",
        "Wailing Essence of Sorrow",
        "Wailing Essence of Spite",
        "Wailing Essence of Suffering",
        "Wailing Essence of Torment",
        "Wailing Essence of Woe",
        "Wailing Essence of Wrath",
        "Wailing Essence of Zeal",
        "Azure Oil",
        "Indigo Oil",
        "Rogue's Marker",
        "Stacked Deck",
        "Tainted Orb of Fusing",
        "Vial of Awakening",
        "Vial of Consequence",
        "Vial of Dominance",
        "Vial of Fate",
        "Vial of Summoning",
        "Vial of Transcendence",
        "Vial of the Ritual",
        "Cartographer's Chisel",
        "Harbinger's Shard",
        "Horizon Shard",
        "Violet Oil",
        "Screaming Essence of Anger",
        "Screaming Essence of Anguish",
        "Screaming Essence of Contempt",
        "Screaming Essence of Doubt",
        "Screaming Essence of Dread",
        "Screaming Essence of Envy",
        "Screaming Essence of Fear",
        "Screaming Essence of Greed",
        "Screaming Essence of Hatred",
        "Screaming Essence of Loathing",
        "Screaming Essence of Misery",
        "Screaming Essence of Rage",
        "Screaming Essence of Scorn",
        "Screaming Essence of Sorrow",
        "Screaming Essence of Spite",
        "Screaming Essence of Suffering",
        "Screaming Essence of Torment",
        "Screaming Essence of Woe",
        "Screaming Essence of Wrath",
        "Screaming Essence of Zeal",
        "Crimson Oil",
        "Veiled Orb",
        "Black Oil",
        "Lesser Eldritch Ember",
        "Lesser Eldritch Ichor",
        "Orb of Horizons",
        "Tainted Divine Teardrop",
        "Veiled Scarab",
        "Vial of Sacrifice",
        "Vial of the Ghost",
        "Blighted Scouting Report",
        "Comprehensive Scouting Report",
        "Delirious Scouting Report",
        "Explorer's Scouting Report",
        "Operative's Scouting Report",
        "Otherworldly Scouting Report",
        "Singular Scouting Report",
        "Fracturing Orb",
        "Fracturing Shard",
        "Orb of Unmaking",
        "Greater Eldritch Ember",
        "Greater Eldritch Ichor",
        "Opalescent Oil",
        "Essence of Delirium",
        "Essence of Horror",
        "Essence of Hysteria",
        "Essence of Insanity",
        "Shrieking Essence of Anger",
        "Shrieking Essence of Anguish",
        "Shrieking Essence of Contempt",
        "Shrieking Essence of Doubt",
        "Shrieking Essence of Dread",
        "Shrieking Essence of Envy",
        "Shrieking Essence of Fear",
        "Shrieking Essence of Greed",
        "Shrieking Essence of Hatred",
        "Shrieking Essence of Loathing",
        "Shrieking Essence of Misery",
        "Shrieking Essence of Rage",
        "Shrieking Essence of Scorn",
        "Shrieking Essence of Sorrow",
        "Shrieking Essence of Spite",
        "Shrieking Essence of Suffering",
        "Shrieking Essence of Torment",
        "Shrieking Essence of Woe",
        "Shrieking Essence of Wrath",
        "Shrieking Essence of Zeal",
        "Vaal Scouting Report",
        "Grand Eldritch Ember",
        "Grand Eldritch Ichor",
        "Silver Oil",
        "Golden Oil",
        "Eldritch Chaos Orb",
        "Eldritch Exalted Orb",
        "Eldritch Orb of Annulment",
        "Exceptional Eldritch Ember",
        "Exceptional Eldritch Ichor",
        "Influenced Scouting Report",
        "Deafening Essence of Anger",
        "Deafening Essence of Anguish",
        "Deafening Essence of Contempt",
        "Deafening Essence of Doubt",
        "Deafening Essence of Dread",
        "Deafening Essence of Envy",
        "Deafening Essence of Fear",
        "Deafening Essence of Greed",
        "Deafening Essence of Hatred",
        "Deafening Essence of Loathing",
        "Deafening Essence of Misery",
        "Deafening Essence of Rage",
        "Deafening Essence of Scorn",
        "Deafening Essence of Sorrow",
        "Deafening Essence of Spite",
        "Deafening Essence of Suffering",
        "Deafening Essence of Torment",
        "Deafening Essence of Woe",
        "Deafening Essence of Wrath",
        "Deafening Essence of Zeal",
        "Crescent Splinter"
    ],
    "Quivers": [
        "Serrated Arrow Quiver",
        "Fire Arrow Quiver",
        "Sharktooth Arrow Quiver",
        "Feathered Arrow Quiver",
        "Penetrating Arrow Quiver",
        "Blunt Arrow Quiver",
        "Two-Point Arrow Quiver",
        "Spike-Point Arrow Quiver",
        "Blazing Arrow Quiver",
        "Ornate Quiver",
        "Broadhead Arrow Quiver",
        "Vile Arrow Quiver",
        "Heavy Arrow Quiver",
        "Primal Arrow Quiver",
        "Artillery Quiver"
    ],
    "Warstaves": [
        "Iron Staff",
        "Coiled Staff",
        "Capacity Rod",
        "Vile Staff",
        "Military Staff",
        "Serpentine Staff",
        "Potentiality Rod",
        "Foul Staff",
        "Ezomyte Staff",
        "Maelström Staff",
        "Judgement Staff",
        "Eventuality Rod"
    ],
    "Two Hand Axes": [
        "Stone Axe",
        "Jade Chopper",
        "Woodsplitter",
        "Poleaxe",
        "Double Axe",
        "Gilded Axe",
        "Prime Cleaver",
        "Shadow Axe",
        "Dagger Axe",
        "Jasper Chopper",
        "Timber Axe",
        "Headsman Axe",
        "Labrys",
        "Honed Cleaver",
        "Noble Axe",
        "Abyssal Axe",
        "Karui Chopper",
        "Talon Axe",
        "Sundering Axe",
        "Ezomyte Axe",
        "Vaal Axe",
        "Despot Axe",
        "Void Axe",
        "Apex Cleaver",
        "Fleshripper"
    ],
    "Heist Cloaks": [
        "Torn Cloak",
        "Tattered Cloak",
        "Hooded Cloak",
        "Whisper-woven Cloak"
    ],
    "Relics": [
        "Candlestick Relic",
        "Censer Relic",
        "Coffer Relic",
        "Papyrus Relic",
        "Processional Relic",
        "Tome Relic",
        "Urn Relic"
    ],
    "Claws": [
        "Nailed Fist",
        "Sharktooth Claw",
        "Awl",
        "Cat's Paw",
        "Blinder",
        "Timeworn Claw",
        "Shadow Fangs",
        "Sparkling Claw",
        "Fright Claw",
        "Double Claw",
        "Thresher Claw",
        "Gouger",
        "Tiger's Paw",
        "Gut Ripper",
        "Prehistoric Claw",
        "Malign Fangs",
        "Noble Claw",
        "Eagle Claw",
        "Twin Claw",
        "Great White Claw",
        "Throat Stabber",
        "Hellion's Paw",
        "Eye Gouger",
        "Vaal Claw",
        "Imperial Claw",
        "Terror Claw",
        "Void Fangs",
        "Gemini Claw"
    ],
    "Helmets": [
        "Iron Hat",
        "Leather Cap",
        "Vine Circlet",
        "Battered Helm",
        "Scare Mask",
        "Rusted Coif",
        "Cone Helmet",
        "Iron Circlet",
        "Plague Mask",
        "Tricorne",
        "Soldier Helmet",
        "Sallet",
        "Gale Crown",
        "Imp Crown",
        "Sorrow Mask",
        "Iron Mask",
        "Torture Cage",
        "Barbute Helmet",
        "Leather Hood",
        "Great Helmet",
        "Visored Sallet",
        "Runic Helm",
        "Close Helmet",
        "Tribal Circlet",
        "Festival Mask",
        "Wolf Pelt",
        "Crusader Helmet",
        "Gilded Sallet",
        "Bone Circlet",
        "Gladiator Helmet",
        "Golden Mask",
        "Secutor Helm",
        "Aventail Helmet",
        "Raven Mask",
        "Lunaris Circlet",
        "Reaver Helmet",
        "Hunter Hood",
        "Fencer Helm",
        "Zealot Helmet",
        "Atonement Mask",
        "Callous Mask",
        "Demon Crown",
        "Winter Crown",
        "Noble Tricorne",
        "Siege Helmet",
        "Steel Circlet",
        "Runic Crest",
        "Lacquered Helmet",
        "Regicide Mask",
        "Great Crown",
        "Necromancer Circlet",
        "Samnite Helmet",
        "Ursine Pelt",
        "Harlequin Mask",
        "Fluted Bascinet",
        "Magistrate Crown",
        "Solaris Circlet",
        "Ezomyte Burgonet",
        "Silken Hood",
        "Vaal Mask",
        "Pig-Faced Bascinet",
        "Prophet Crown",
        "Sinner Tricorne",
        "Mind Cage",
        "Royal Burgonet",
        "Deicide Mask",
        "Nightmare Bascinet",
        "Praetor Crown",
        "Runic Crown",
        "Eternal Burgonet",
        "Hubris Circlet",
        "Lion Pelt",
        "Bone Helmet",
        "Archdemon Crown",
        "Blizzard Crown",
        "Penitent Mask"
    ],
    "Two Hand Swords": [
        "Corroded Blade",
        "Longsword",
        "Bastard Sword",
        "Two-Handed Sword",
        "Etched Greatsword",
        "Ornate Sword",
        "Rebuking Blade",
        "Spectral Sword",
        "Curved Blade",
        "Butcher Sword",
        "Footman Sword",
        "Highland Blade",
        "Engraved Greatsword",
        "Blasting Blade",
        "Tiger Sword",
        "Wraith Sword",
        "Lithe Blade",
        "Headman's Sword",
        "Reaver Sword",
        "Ezomyte Blade",
        "Vaal Greatsword",
        "Lion Sword",
        "Infernal Sword",
        "Banishing Blade",
        "Exquisite Blade"
    ],
    "Jewels": [
        "Large Cluster Jewel",
        "Medium Cluster Jewel",
        "Prismatic Jewel",
        "Small Cluster Jewel",
        "Cobalt Jewel",
        "Crimson Jewel",
        "Timeless Jewel",
        "Viridian Jewel"
    ],
    "Map Fragments": [
        "Blood-filled Vessel",
        "Dedication to the Goddess",
        "Gift to the Goddess",
        "Offering to the Goddess",
        "Sacred Blossom",
        "Tribute to the Goddess",
        "Sacrifice at Dawn",
        "Sacrifice at Dusk",
        "Sacrifice at Noon",
        "Divine Vessel",
        "Sacrifice at Midnight",
        "Abyss Scarab",
        "Abyss Scarab of Edifice",
        "Abyss Scarab of Emptiness",
        "Abyss Scarab of Multitudes",
        "Abyss Scarab of Profound Depth",
        "Ambush Scarab",
        "Ambush Scarab of Containment",
        "Ambush Scarab of Discernment",
        "Ambush Scarab of Hidden Compartments",
        "Ambush Scarab of Potency",
        "Anarchy Scarab",
        "Anarchy Scarab of Gigantification",
        "Anarchy Scarab of Partnership",
        "Bestiary Scarab",
        "Bestiary Scarab of Duplicating",
        "Bestiary Scarab of the Herd",
        "Bestiary Scarab of the Shadowed Crow",
        "Betrayal Scarab",
        "Betrayal Scarab of Intelligence",
        "Betrayal Scarab of Perpetuation",
        "Betrayal Scarab of Reinforcements",
        "Beyond Scarab",
        "Beyond Scarab of Corruption",
        "Beyond Scarab of Haemophilia",
        "Beyond Scarab of Resurgence",
        "Beyond Scarab of the Invasion",
        "Blight Scarab",
        "Blight Scarab of Blooming",
        "Blight Scarab of Bounty",
        "Blight Scarab of Invigoration",
        "Blight Scarab of Oils",
        "Breach Scarab",
        "Breach Scarab of Lordship",
        "Breach Scarab of Resonant Cascade",
        "Breach Scarab of Snares",
        "Breach Scarab of Splintering",
        "Breach Scarab of the Dreamer",
        "Cartography Scarab",
        "Cartography Scarab of Ascension",
        "Cartography Scarab of Corruption",
        "Cartography Scarab of Duplication",
        "Cartography Scarab of Singularity",
        "Delirium Scarab",
        "Delirium Scarab of Delusions",
        "Delirium Scarab of Mania",
        "Delirium Scarab of Neuroses",
        "Delirium Scarab of Paranoia",
        "Divination Scarab",
        "Divination Scarab of Completion",
        "Divination Scarab of Curation",
        "Domination Scarab",
        "Domination Scarab of Abnormality",
        "Domination Scarab of Teachings",
        "Domination Scarab of Terrors",
        "Essence Scarab",
        "Essence Scarab of Adaptation",
        "Essence Scarab of Ascent",
        "Essence Scarab of Calcification",
        "Essence Scarab of Stability",
        "Expedition Scarab",
        "Expedition Scarab of Archaeology",
        "Expedition Scarab of Runefinding",
        "Expedition Scarab of Verisium Powder",
        "Expedition Scarab of the Skald",
        "Harbinger Scarab",
        "Harbinger Scarab of Discernment",
        "Harbinger Scarab of Regency",
        "Harbinger Scarab of Warhoards",
        "Harvest Scarab",
        "Harvest Scarab of Cornucopia",
        "Harvest Scarab of Doubling",
        "Horned Scarab of Awakening",
        "Horned Scarab of Bloodlines",
        "Horned Scarab of Glittering",
        "Horned Scarab of Nemeses",
        "Horned Scarab of Pandemonium",
        "Horned Scarab of Preservation",
        "Horned Scarab of Tradition",
        "Incursion Scarab",
        "Incursion Scarab of Champions",
        "Incursion Scarab of Invasion",
        "Incursion Scarab of Timelines",
        "Influencing Scarab of Conversion",
        "Influencing Scarab of Hordes",
        "Influencing Scarab of the Elder",
        "Influencing Scarab of the Shaper",
        "Legion Scarab",
        "Legion Scarab of Command",
        "Legion Scarab of Eternal Conflict",
        "Legion Scarab of Officers",
        "Legion Scarab of The Sekhema",
        "Mysterious Scarab",
        "Reliquary Scarab",
        "Reliquary Scarab of Overlords",
        "Reliquary Scarab of Vision",
        "Ritual Scarab of Abundance",
        "Ritual Scarab of Recognition",
        "Ritual Scarab of Selectiveness",
        "Scarab of Adversaries",
        "Scarab of Hunted Traitors",
        "Scarab of Monstrous Lineage",
        "Scarab of Radiant Storms",
        "Scarab of Stability",
        "Scarab of Wisps",
        "Sulphite Scarab",
        "Sulphite Scarab of Fumes",
        "Sulphite Scarab of Greed",
        "Torment Scarab",
        "Torment Scarab of Peculiarity",
        "Torment Scarab of Possession",
        "Torment Scarab of Release",
        "Ultimatum Scarab",
        "Ultimatum Scarab of Bribing",
        "Ultimatum Scarab of Catalysing",
        "Ultimatum Scarab of Dueling",
        "Ultimatum Scarab of Inscription",
        "Mortal Grief",
        "Mortal Hope",
        "Mortal Ignorance",
        "Mortal Rage",
        "Simulacrum",
        "Timeless Eternal Emblem",
        "Timeless Karui Emblem",
        "Timeless Maraketh Emblem",
        "Timeless Templar Emblem",
        "Timeless Vaal Emblem",
        "Unrelenting Timeless Eternal Emblem",
        "Unrelenting Timeless Karui Emblem",
        "Unrelenting Timeless Maraketh Emblem",
        "Unrelenting Timeless Templar Emblem",
        "Unrelenting Timeless Vaal Emblem",
        "Al-Hezmin's Crest",
        "Baran's Crest",
        "Drox's Crest",
        "Fragment of Constriction",
        "Fragment of Emptiness",
        "Fragment of Enslavement",
        "Fragment of Eradication",
        "Fragment of Knowledge",
        "Fragment of Purification",
        "Fragment of Shape",
        "Fragment of Terror",
        "Veritania's Crest",
        "The Maven's Writ",
        "Awakening Fragment",
        "Blazing Fragment",
        "Cosmic Fragment",
        "Decaying Fragment",
        "Devouring Fragment",
        "Fragment of the Chimera",
        "Fragment of the Hydra",
        "Fragment of the Minotaur",
        "Fragment of the Phoenix",
        "Reality Fragment",
        "Synthesising Fragment"
    ],
    "Expedition Logbooks": ["Expedition Logbook"],
    "Sentinel Drones": [
        "Ancient Apex Sentinel",
        "Ancient Pandemonium Sentinel",
        "Ancient Stalker Sentinel",
        "Brimstone Apex Sentinel",
        "Brimstone Pandemonium Sentinel",
        "Brimstone Stalker Sentinel",
        "Bronze Apex Sentinel",
        "Bronze Pandemonium Sentinel",
        "Bronze Stalker Sentinel",
        "Cobalt Apex Sentinel",
        "Cobalt Pandemonium Sentinel",
        "Cobalt Stalker Sentinel",
        "Cosmic Apex Sentinel",
        "Cryptic Apex Sentinel",
        "Cryptic Pandemonium Sentinel",
        "Cryptic Stalker Sentinel",
        "Emberstone Apex Sentinel",
        "Emberstone Pandemonium Sentinel",
        "Emberstone Stalker Sentinel",
        "Obsidian Apex Sentinel",
        "Obsidian Pandemonium Sentinel",
        "Obsidian Stalker Sentinel",
        "Primeval Apex Sentinel",
        "Primeval Pandemonium Sentinel",
        "Primeval Stalker Sentinel",
        "Rusted Stalker Sentinel"
    ],
    "Blueprints": [
        "Blueprint: Bunker",
        "Blueprint: Mansion",
        "Blueprint: Records Office",
        "Blueprint: Smuggler's Den",
        "Blueprint: Underbelly",
        "Blueprint: Repository",
        "Blueprint: Tunnels",
        "Blueprint: Laboratory",
        "Blueprint: Prohibited Library"
    ],
    "Support Gems": [
        "Controlled Blaze Support",
        "Corrupting Cry Support",
        "Cursed Ground Support",
        "Devour Support",
        "Flamewood Support",
        "Fresh Meat Support",
        "Frigid Bond Support",
        "Guardian's Blessing Support",
        "Hex Bloom Support",
        "Locus Mine Support",
        "Manaforged Arrows Support",
        "Momentum Support",
        "Prismatic Burst Support",
        "Returning Projectiles Support",
        "Sacred Wisps Support",
        "Sacrifice Support",
        "Sadism Support",
        "Spellblade Support",
        "Trauma Support",
        "Volatility Support",
        "Ancestral Call Support",
        "Arcane Surge Support",
        "Chance to Bleed Support",
        "Chance to Poison Support",
        "Elemental Proliferation Support",
        "Infused Channelling Support",
        "Mirage Archer Support",
        "Pierce Support",
        "Ruthless Support",
        "Spell Cascade Support",
        "Summon Phantasm Support",
        "Swift Assembly Support",
        "Volley Support",
        "Added Cold Damage Support",
        "Added Fire Damage Support",
        "Added Lightning Damage Support",
        "Additional Accuracy Support",
        "Arrow Nova Support",
        "Ballista Totem Support",
        "Blastchain Mine Support",
        "Blind Support",
        "Chance to Flee Support",
        "Combustion Support",
        "Earthbreaker Support",
        "Efficacy Support",
        "Increased Critical Strikes Support",
        "Infernal Legion Support",
        "Knockback Support",
        "Lesser Multiple Projectiles Support",
        "Life Gain on Hit Support",
        "Lifetap Support",
        "Maim Support",
        "Melee Splash Support",
        "Minion Damage Support",
        "Multiple Traps Support",
        "Spell Totem Support",
        "Stun Support",
        "Trap Support",
        "Unbound Ailments Support",
        "Void Manipulation Support",
        "Block Chance Reduction Support",
        "Bloodlust Support",
        "Close Combat Support",
        "Cold to Fire Support",
        "Concentrated Effect Support",
        "Controlled Destruction Support",
        "Cruelty Support",
        "Culling Strike Support",
        "Damage on Full Life Support",
        "Deadly Ailments Support",
        "Elemental Damage with Attacks Support",
        "Elemental Focus Support",
        "Endurance Charge on Melee Stun Support",
        "Faster Attacks Support",
        "Faster Casting Support",
        "Increased Critical Damage Support",
        "Iron Grip Support",
        "Iron Will Support",
        "Melee Physical Damage Support",
        "Minion Life Support",
        "Minion Speed Support",
        "Nightblade Support",
        "Overcharge Support",
        "Physical to Lightning Support",
        "Point Blank Support",
        "Power Charge On Critical Support",
        "Predator Support",
        "Rage Support",
        "Shockwave Support",
        "Trap and Mine Damage Support",
        "Trinity Support",
        "Vicious Projectiles Support",
        "Item Quantity Support",
        "Added Chaos Damage Support",
        "Advanced Traps Support",
        "Archmage Support",
        "Arrogance Support",
        "Blasphemy Support",
        "Bloodthirst Support",
        "Burning Damage Support",
        "Charged Mines Support",
        "Charged Traps Support",
        "Cold Penetration Support",
        "Critical Strike Affliction Support",
        "Divine Blessing Support",
        "Elemental Army Support",
        "Elemental Penetration Support",
        "Energy Leech Support",
        "Faster Projectiles Support",
        "Feeding Frenzy Support",
        "Fire Penetration Support",
        "Focused Ballista Support",
        "Fork Support",
        "Fortify Support",
        "Generosity Support",
        "High-Impact Mine Support",
        "Hypothermia Support",
        "Ice Bite Support",
        "Impale Support",
        "Impending Doom Support",
        "Increased Duration Support",
        "Innervate Support",
        "Inspiration Support",
        "Intensify Support",
        "Item Rarity Support",
        "Less Duration Support",
        "Life Leech Support",
        "Lightning Penetration Support",
        "Mana Leech Support",
        "Meat Shield Support",
        "Pinpoint Support",
        "Pulverise Support",
        "Second Wind Support",
        "Slower Projectiles Support",
        "Swift Affliction Support",
        "Swiftbrand Support",
        "Urgent Orders Support",
        "Barrage Support",
        "Behead Support",
        "Bonechill Support",
        "Brutality Support",
        "Cast On Critical Strike Support",
        "Cast on Death Support",
        "Cast on Melee Kill Support",
        "Cast when Damage Taken Support",
        "Cast when Stunned Support",
        "Cast while Channelling Support",
        "Chain Support",
        "Cluster Traps Support",
        "Decay Support",
        "Empower Support",
        "Enhance Support",
        "Enlighten Support",
        "Eternal Blessing Support",
        "Fist of War Support",
        "Greater Multiple Projectiles Support",
        "Greater Volley Support",
        "Hextouch Support",
        "Ignite Proliferation Support",
        "Immolate Support",
        "Increased Area of Effect Support",
        "Mark On Hit Support",
        "Minefield Support",
        "Multiple Totems Support",
        "Multistrike Support",
        "Spell Echo Support",
        "Unleash Support",
        "Vile Toxins Support",
        "Withering Touch Support",
        "Awakened Added Chaos Damage Support",
        "Awakened Added Cold Damage Support",
        "Awakened Added Fire Damage Support",
        "Awakened Added Lightning Damage Support",
        "Awakened Ancestral Call Support",
        "Awakened Arrow Nova Support",
        "Awakened Blasphemy Support",
        "Awakened Brutality Support",
        "Awakened Burning Damage Support",
        "Awakened Cast On Critical Strike Support",
        "Awakened Cast While Channelling Support",
        "Awakened Chain Support",
        "Awakened Cold Penetration Support",
        "Awakened Controlled Destruction Support",
        "Awakened Deadly Ailments Support",
        "Awakened Elemental Damage with Attacks Support",
        "Awakened Elemental Focus Support",
        "Awakened Empower Support",
        "Awakened Enhance Support",
        "Awakened Enlighten Support",
        "Awakened Fire Penetration Support",
        "Awakened Fork Support",
        "Awakened Generosity Support",
        "Awakened Greater Multiple Projectiles Support",
        "Awakened Hextouch Support",
        "Awakened Increased Area of Effect Support",
        "Awakened Lightning Penetration Support",
        "Awakened Melee Physical Damage Support",
        "Awakened Melee Splash Support",
        "Awakened Minion Damage Support",
        "Awakened Multistrike Support",
        "Awakened Spell Cascade Support",
        "Awakened Spell Echo Support",
        "Awakened Swift Affliction Support",
        "Awakened Unbound Ailments Support",
        "Awakened Unleash Support",
        "Awakened Vicious Projectiles Support",
        "Awakened Void Manipulation Support"
    ],
    "Trinkets": ["Thief's Trinket"],
    "Labyrinth Items": [
        "Golden Key",
        "Silver Key",
        "Treasure Key"
    ],
    "One Hand Maces": [
        "Driftwood Club",
        "Tribal Club",
        "Spiked Club",
        "Stone Hammer",
        "War Hammer",
        "Bladed Mace",
        "Ceremonial Mace",
        "Flare Mace",
        "Dream Mace",
        "Wyrm Mace",
        "Petrified Club",
        "Barbed Club",
        "Rock Breaker",
        "Battle Hammer",
        "Flanged Mace",
        "Crack Mace",
        "Ornate Mace",
        "Phantom Mace",
        "Dragon Mace",
        "Ancestral Club",
        "Tenderizer",
        "Gavel",
        "Legion Hammer",
        "Pernach",
        "Auric Mace",
        "Nightmare Mace",
        "Behemoth Mace",
        "Boom Mace"
    ],
    "Body Armours": [
        "Plate Vest",
        "Shabby Jerkin",
        "Simple Robe",
        "Chainmail Vest",
        "Padded Vest",
        "Scale Vest",
        "Chestplate",
        "Chainmail Tunic",
        "Light Brigandine",
        "Oiled Vest",
        "Strapped Leather",
        "Silken Vest",
        "Buckskin Tunic",
        "Copper Plate",
        "Ringmail Coat",
        "Scale Doublet",
        "Padded Jacket",
        "Scholar's Robe",
        "Chainmail Doublet",
        "Infantry Brigandine",
        "War Plate",
        "Oiled Coat",
        "Silken Garb",
        "Wild Leather",
        "Full Leather",
        "Full Plate",
        "Full Ringmail",
        "Full Scale Armour",
        "Mage's Vestment",
        "Scarlet Raiment",
        "Arena Plate",
        "Full Chainmail",
        "Silk Robe",
        "Soldier's Brigandine",
        "Sun Leather",
        "Waxed Garb",
        "Bone Armour",
        "Cabalist Regalia",
        "Field Lamellar",
        "Holy Chainmail",
        "Lordly Plate",
        "Thief's Garb",
        "Bronze Plate",
        "Eelskin Tunic",
        "Sage's Robe",
        "Wyrmscale Doublet",
        "Latticed Ringmail",
        "Quilted Jacket",
        "Battle Plate",
        "Frontier Leather",
        "Silken Wrap",
        "Hussar Brigandine",
        "Crusader Chainmail",
        "Sleek Coat",
        "Conjurer's Vestment",
        "Glorious Leather",
        "Sun Plate",
        "Full Wyrmscale",
        "Ornate Ringmail",
        "Crimson Raiment",
        "Colosseum Plate",
        "Coronal Leather",
        "Spidersilk Robe",
        "Commander's Brigandine",
        "Chain Hauberk",
        "Lacquered Garb",
        "Cutthroat's Garb",
        "Destroyer Regalia",
        "Majestic Plate",
        "Battle Lamellar",
        "Devout Chainmail",
        "Crypt Armour",
        "Golden Plate",
        "Savant's Robe",
        "Sharkskin Tunic",
        "Dragonscale Doublet",
        "Loricated Ringmail",
        "Crusader Plate",
        "Destiny Leather",
        "Necromancer Silks",
        "Sentinel Jacket",
        "Desert Brigandine",
        "Conquest Chainmail",
        "Astral Plate",
        "Exquisite Leather",
        "Occultist's Vestment",
        "Varnished Coat",
        "Full Dragonscale",
        "Elegant Ringmail",
        "Blood Raiment",
        "Gladiator Plate",
        "Widowsilk Robe",
        "Zodiac Leather",
        "General's Brigandine",
        "Saint's Hauberk",
        "Assassin's Garb",
        "Glorious Plate",
        "Sadist Garb",
        "Vaal Regalia",
        "Triumphant Lamellar",
        "Grasping Mail",
        "Saintly Chainmail",
        "Carnal Armour",
        "Sacrificial Garb"
    ],
    "Divination Cards": [
        "A Chilling Wind",
        "A Dusty Memory",
        "Alivia's Grace",
        "Assassin's Gift",
        "Auspicious Ambitions",
        "Brother's Gift",
        "Divine Beauty",
        "Eldritch Perfection",
        "Ever-Changing",
        "Fire Of Unknown Origin",
        "I See Brothers",
        "Man With Bear",
        "Matryoshka",
        "Poisoned Faith",
        "Soul Quenched",
        "The Finishing Touch",
        "The Fortunate",
        "The Insane Cat",
        "The Return of the Rat",
        "The Wedding Gift",
        "Who Asked",
        "A Dab of Ink",
        "A Mother's Parting Gift",
        "Acclimatisation",
        "Akil's Prophecy",
        "Assassin's Favour",
        "Atziri's Arsenal",
        "Baited Expectations",
        "Blind Venture",
        "Call to the First Ones",
        "Chaotic Disposition",
        "Coveted Possession",
        "Dialla's Subjugation",
        "Doedre's Madness",
        "Earth Drinker",
        "Emperor's Luck",
        "Gemcutter's Promise",
        "Grave Knowledge",
        "Her Mask",
        "Heterochromia",
        "Hubris",
        "Humility",
        "Hunter's Resolve",
        "Hunter's Reward",
        "Jack in the Box",
        "Lantador's Lost Love",
        "Loyalty",
        "Lucky Connections",
        "Lysah's Respite",
        "Mitts",
        "No Traces",
        "Rain of Chaos",
        "Rebirth",
        "Shard of Fate",
        "Society's Remorse",
        "The Aesthete",
        "The Battle Born",
        "The Betrayal",
        "The Body",
        "The Brittle Emperor",
        "The Cache",
        "The Calling",
        "The Carrion Crow",
        "The Catalyst",
        "The Craving",
        "The Cursed King",
        "The Deceiver",
        "The Doppelganger",
        "The Dragon",
        "The Drunken Aristocrat",
        "The Endurance",
        "The Eye of the Dragon",
        "The Fishmonger",
        "The Fool",
        "The Forsaken",
        "The Garish Power",
        "The Gemcutter",
        "The Gentleman",
        "The Hermit",
        "The Heroic Shot",
        "The Innocent",
        "The Inventor",
        "The Lion",
        "The Lover",
        "The Master",
        "The Master Artisan",
        "The Mercenary",
        "The Metalsmith's Gift",
        "The Mountain",
        "The One With All",
        "The Opulent",
        "The Poet",
        "The Polymath",
        "The Primordial",
        "The Realm",
        "The Ruthless Ceinture",
        "The Scarred Meadow",
        "The Scholar",
        "The Skeleton",
        "The Spark and the Flame",
        "The Standoff",
        "The Summoner",
        "The Survivalist",
        "The Sword King's Salute",
        "The Thaumaturgist",
        "The Tower",
        "The Traitor",
        "The Undaunted",
        "The Union",
        "The Valkyrie",
        "The Vast",
        "The Void",
        "The Warden",
        "The Witch",
        "The Wolverine",
        "The Wrath",
        "Three Faces in the Dark",
        "Three Voices",
        "Thunderous Skies",
        "Turn the Other Cheek",
        "Vanity",
        "Vile Power",
        "Volatile Power",
        "The Siren",
        "The Army of Blood",
        "The Fletcher",
        "The Mad King",
        "The Harvester",
        "The Insatiable",
        "Might is Right",
        "The Lich",
        "The Nurse",
        "Light and Truth",
        "The Offspring",
        "Alone in the Darkness",
        "Lachrymal Necrosis",
        "The Tinkerer's Table",
        "Demigod's Wager",
        "Seven Years Bad Luck",
        "The Beast",
        "The Immortal",
        "The Seeker",
        "The Sephirot",
        "Unrequited Love",
        "Thirst for Knowledge",
        "The Lunaris Priestess",
        "Gemcutter's Mercy",
        "Glimmer of Hope",
        "Home",
        "The Academic",
        "The Chains that Bind",
        "The Hunger",
        "The Porcupine",
        "The Strategist",
        "The Adventuring Spirit",
        "The Cartographer",
        "Echoes of Love",
        "Rats",
        "Dark Temptation",
        "A Note in the Wind",
        "Disdain",
        "Forbidden Power",
        "The Avenger",
        "The Coming Storm",
        "The Feast",
        "The Rusted Bard",
        "The Wolf",
        "The Blazing Fire",
        "The Celestial Justicar",
        "The Oath",
        "The Offering",
        "The Scavenger",
        "The Wolf's Shadow",
        "Anarchy's Price",
        "The Pack Leader",
        "Tranquillity",
        "The Deep Ones",
        "The Risk",
        "The Soul",
        "The Sun",
        "A Stone Perfected",
        "Emperor of Purity",
        "The Dark Mage",
        "The Forward Gaze",
        "The Fox in the Brambles",
        "The Rabbit's Foot",
        "The Stormcaller",
        "Death",
        "Pride Before the Fall",
        "The Ethereal",
        "The Formless Sea",
        "The King's Heart",
        "The Pact",
        "The Throne",
        "The Whiteout",
        "Audacity",
        "The Conduit",
        "The Watcher",
        "Last Hope",
        "The Visionary",
        "Arrogance of the Vaal",
        "Love Through Ice",
        "Reckless Ambition",
        "The Damned",
        "The Demoness",
        "The Enthusiasts",
        "The Old Man",
        "From Bone to Ashes",
        "The Gladiator",
        "Beauty Through Death",
        "Divine Justice",
        "The Escape",
        "Boundless Realms",
        "Cartographer's Delight",
        "Etched in Blood",
        "Rain Tempter",
        "Sambodhi's Wisdom",
        "The Last Supper",
        "The Sigil",
        "The Wolven King's Bite",
        "The Inoculated",
        "The Enlightened",
        "The Flora's Gift",
        "The King's Blade",
        "The Surgeon",
        "Prosperity",
        "Broken Truce",
        "A Modest Request",
        "A Sea of Blue",
        "Abandoned Wealth",
        "Alluring Bounty",
        "Altered Perception",
        "Ambitious Obsession",
        "Astral Protection",
        "Azyran's Reward",
        "Brother's Stash",
        "Brotherhood in Exile",
        "Brush, Paint and Palette",
        "Buried Treasure",
        "Cameria's Cut",
        "Checkmate",
        "Cursed Words",
        "Deadly Joy",
        "Dementophobia",
        "Desperate Crusade",
        "Doryani's Epiphany",
        "Dying Anguish",
        "Endless Night",
        "Gift of Asenath",
        "Gift of the Gemling Queen",
        "Harmony of Souls",
        "Haunting Shadows",
        "Hope",
        "Luminous Trove",
        "Mawr Blaidd",
        "More is Never Enough",
        "Parasitic Passengers",
        "Peaceful Moments",
        "Rebirth and Renewal",
        "Remembrance",
        "Scholar of the Seas",
        "The Artist",
        "The Blessing of Moosh",
        "The Breach",
        "The Cacophony",
        "The Card Sharp",
        "The Catch",
        "The Deal",
        "The Demon",
        "The Doctor",
        "The Dreamer",
        "The Dreamland",
        "The Dungeon Master",
        "The Eternal War",
        "The Explorer",
        "The Eye of Terror",
        "The Fiend",
        "The Fox",
        "The Gambler",
        "The Hive of Knowledge",
        "The Hoarder",
        "The Incantation",
        "The Journalist",
        "The Journey",
        "The Life Thief",
        "The Messenger",
        "The Mind's Eyes",
        "The Obscured",
        "The Patient",
        "The Penitent",
        "The Prince of Darkness",
        "The Professor",
        "The Puzzle",
        "The Saint's Treasure",
        "The Scout",
        "The Tireless Extractor",
        "The Transformation",
        "The Twilight Moon",
        "The Unexpected Prize",
        "The Web",
        "The Wind",
        "The Wolf's Legacy",
        "The Wretched",
        "Time-Lost Relic",
        "Treasure Hunter",
        "Unchained",
        "Vinia's Token",
        "Wealth and Power",
        "Winter's Embrace",
        "The Side Quest",
        "Burning Blood",
        "Misery in Darkness",
        "Sambodhi's Vow",
        "Silence and Frost",
        "Struck by Lightning",
        "The Admirer",
        "The Fathomless Depths",
        "The Shieldbearer",
        "Boon of the First Ones",
        "Deathly Designs",
        "Desecrated Virtue",
        "Terrible Secret of Space",
        "The Bitter Blossom",
        "The Bones",
        "The Cataclysm",
        "The Cheater",
        "The Hook",
        "The Magma Crab",
        "The Rite of Elements",
        "The Wilted Rose",
        "Boon of Justice",
        "Left to Fate",
        "Lost Worlds",
        "The Arena Champion",
        "The Easy Stroll",
        "The Encroaching Darkness",
        "The Landing",
        "The Surveyor",
        "The Trial",
        "Lucky Deck",
        "Judging Voices",
        "Something Dark",
        "The Apothecary",
        "The Lord in Black",
        "The Price of Devotion",
        "The Rabid Rhoa",
        "The Twins",
        "The Warlord",
        "A Fate Worse Than Death",
        "Eternal Bonds",
        "House of Mirrors",
        "Lethean Temptation",
        "Lingering Remnants",
        "The Dragon's Heart",
        "The One That Got Away",
        "The Price of Prescience",
        "Succor of the Sinless",
        "The Price of Loyalty",
        "A Familiar Call",
        "Bijoux",
        "Bowyer's Dream",
        "Broken Promises",
        "Choking Guilt",
        "Costly Curio",
        "Council of Cats",
        "Dark Dreams",
        "Destined to Crumble",
        "Draped in Dreams",
        "Duality",
        "Dying Light",
        "Fateful Meeting",
        "Further Invention",
        "Immortal Resolve",
        "Imperfect Memories",
        "Imperial Legacy",
        "Keeper's Corruption",
        "Magnum Opus",
        "Merciless Armament",
        "Monochrome",
        "Nook's Crown",
        "Perfection",
        "Prejudice",
        "Pride of the First Ones",
        "Prometheus' Armoury",
        "The Archmage's Right Hand",
        "The Awakened",
        "The Bear Woman",
        "The Brawny Battle Mage",
        "The Celestial Stone",
        "The Chosen",
        "The Dapper Prodigy",
        "The Darkest Dream",
        "The Emptiness",
        "The Enforcer",
        "The Forgotten Treasure",
        "The Golden Era",
        "The Hale Heart",
        "The Jester",
        "The Jeweller's Boon",
        "The Last One Standing",
        "The Long Con",
        "The Lord of Celebration",
        "The Queen",
        "The Road to Power",
        "The Sacrifice",
        "The Shepherd's Sandals",
        "The Shortcut",
        "The Spoiled Prince",
        "The Tumbleweed",
        "The Tyrant",
        "The Undisputed",
        "The White Knight",
        "Triskaidekaphobia",
        "Underground Forest",
        "Void of the Elements",
        "Azure Rage",
        "Chasing Risk",
        "Darker Half",
        "Guardian's Challenge",
        "Justified Ambition",
        "The Aspirant",
        "The Astromancer",
        "The Destination",
        "The Eldritch Decay",
        "The Endless Darkness",
        "The Greatest Intentions",
        "The Leviathan",
        "The Price of Protection",
        "The Progeny of Lunaris",
        "The Samurai's Eye",
        "The World Eater",
        "The Gulf"
    ],
    "Two Hand Maces": [
        "Driftwood Maul",
        "Tribal Maul",
        "Mallet",
        "Sledgehammer",
        "Jagged Maul",
        "Brass Maul",
        "Blunt Force Condenser",
        "Fright Maul",
        "Morning Star",
        "Totemic Maul",
        "Great Mallet",
        "Steelhead",
        "Spiny Maul",
        "Crushing Force Magnifier",
        "Plated Maul",
        "Dread Maul",
        "Solar Maul",
        "Karui Maul",
        "Colossus Mallet",
        "Piledriver",
        "Meatgrinder",
        "Imperial Maul",
        "Terror Maul",
        "Coronal Maul",
        "Impact Force Propagator"
    ],
    "Sanctum Research": [
        "Forbidden Tome",
        "Sanctum Archives Research",
        "Sanctum Cathedral Research",
        "Sanctum Necropolis Research",
        "Sanctum Vaults Research"
    ],
    "Contracts": [
        "Contract: Bunker",
        "Contract: Underbelly",
        "Contract: Mansion",
        "Contract: Records Office",
        "Contract: Smuggler's Den",
        "Contract: Repository",
        "Contract: Tunnels",
        "Contract: Laboratory",
        "Contract: Prohibited Library",
        "Preventative Contract",
        "Vigilante Contract",
        "Familial Contract",
        "Naval Contract",
        "Vengeful Contract"
    ],
    "Heist Brooches": [
        "Silver Brooch",
        "Golden Brooch",
        "Enamel Brooch",
        "Foliate Brooch"
    ],
    "Heist Gear": [
        "Flanged Arrowhead",
        "Focal Stone",
        "Rough Sharpening Stone",
        "Conduit Line",
        "Fragmenting Arrowhead",
        "Standard Sharpening Stone",
        "Aggregator Charm",
        "Fine Sharpening Stone",
        "Hollowpoint Arrowhead",
        "Burst Band",
        "Obsidian Sharpening Stone",
        "Precise Arrowhead"
    ],
    "Heist Targets": ["Urn of Farud"],
    "Mana Flasks": [
        "Small Mana Flask",
        "Medium Mana Flask",
        "Large Mana Flask",
        "Greater Mana Flask",
        "Grand Mana Flask",
        "Giant Mana Flask",
        "Colossal Mana Flask",
        "Sacred Mana Flask",
        "Hallowed Mana Flask",
        "Sanctified Mana Flask",
        "Divine Mana Flask",
        "Eternal Mana Flask"
    ],
    "Rune Daggers": [
        "Carving Knife",
        "Boot Knife",
        "Copper Kris",
        "Skean",
        "Flickerflame Blade",
        "Imp Dagger",
        "Butcher Knife",
        "Boot Blade",
        "Golden Kris",
        "Flashfire Blade",
        "Royal Skean",
        "Fiend Dagger",
        "Slaughter Knife",
        "Ezomyte Dagger",
        "Platinum Kris",
        "Imperial Skean",
        "Demon Dagger",
        "Infernal Blade"
    ],
    "Heist Tools": [
        "Basic Disguise Kit",
        "Crude Sensing Charm",
        "Crude Ward",
        "Eelskin Sole",
        "Essential Keyring",
        "Leather Bracers",
        "Simple Lockpick",
        "Steel Drill",
        "Voltaxic Flashpowder",
        "Fine Sensing Charm",
        "Flanged Drill",
        "Foxhide Sole",
        "Lustrous Ward",
        "Standard Lockpick",
        "Studded Bracers",
        "Theatre Disguise Kit",
        "Trarthan Flashpowder",
        "Versatile Keyring",
        "Azurite Flashpowder",
        "Espionage Disguise Kit",
        "Fine Lockpick",
        "Polished Sensing Charm",
        "Runed Bracers",
        "Shining Ward",
        "Skeleton Keyring",
        "Sulphur Blowtorch",
        "Winged Sole",
        "Grandmaster Keyring",
        "Master Lockpick",
        "Regicide Disguise Kit",
        "Silkweave Sole",
        "Steel Bracers",
        "Thaumaturgical Sensing Charm",
        "Thaumaturgical Ward",
        "Thaumetic Blowtorch",
        "Thaumetic Flashpowder"
    ],
    "One Hand Axes": [
        "Rusted Hatchet",
        "Jade Hatchet",
        "Boarding Axe",
        "Cleaver",
        "Broad Axe",
        "Arming Axe",
        "Decorative Axe",
        "Maltreatment Axe",
        "Spectral Axe",
        "Etched Hatchet",
        "Jasper Axe",
        "Tomahawk",
        "Wrist Chopper",
        "War Axe",
        "Chest Splitter",
        "Disapprobation Axe",
        "Ceremonial Axe",
        "Wraith Axe",
        "Engraved Hatchet",
        "Karui Axe",
        "Siege Axe",
        "Reaver Axe",
        "Butcher Axe",
        "Vaal Hatchet",
        "Royal Axe",
        "Infernal Axe",
        "Psychotic Axe",
        "Runic Hatchet"
    ],
    "Corpses": [
        "Blasphemer",
        "Dark Reaper",
        "Eldritch Eye",
        "Fiery Cannibal",
        "Frozen Cannibal",
        "Imperfect Blasphemer",
        "Imperfect Dark Marionette",
        "Imperfect Dark Reaper",
        "Imperfect Eldritch Eye",
        "Imperfect Fiery Cannibal",
        "Imperfect Frozen Cannibal",
        "Imperfect Hydra",
        "Imperfect Primal Demiurge",
        "Imperfect Serpent Warrior",
        "Perfect Dark Reaper",
        "Perfect Hydra",
        "Perfect Serpent Warrior",
        "Serpent Warrior"
    ],
    "Tinctures": [
        "Ashbark Tincture",
        "Blood Sap Tincture",
        "Borealwood Tincture",
        "Fulgurite Tincture",
        "Ironwood Tincture",
        "Oakbranch Tincture",
        "Poisonberry Tincture",
        "Rosethorn Tincture"
    ],
    "Hybrid Flasks": [
        "Small Hybrid Flask",
        "Medium Hybrid Flask",
        "Large Hybrid Flask",
        "Colossal Hybrid Flask",
        "Sacred Hybrid Flask",
        "Hallowed Hybrid Flask"
    ],
    "Boots": [
        "Iron Greaves",
        "Rawhide Boots",
        "Wool Shoes",
        "Chain Boots",
        "Leatherscale Boots",
        "Wrapped Boots",
        "Steel Greaves",
        "Velvet Slippers",
        "Goathide Boots",
        "Ringmail Boots",
        "Strapped Boots",
        "Ironscale Boots",
        "Basemetal Treads",
        "Cloudwhisper Boots",
        "Duskwalk Slippers",
        "Deerskin Boots",
        "Silk Slippers",
        "Plated Greaves",
        "Runic Greaves",
        "Clasped Boots",
        "Mesh Boots",
        "Bronzescale Boots",
        "Scholar Boots",
        "Reinforced Greaves",
        "Nubuck Boots",
        "Shackled Boots",
        "Riveted Boots",
        "Steelscale Boots",
        "Antique Greaves",
        "Satin Slippers",
        "Eelskin Boots",
        "Zealot Boots",
        "Trapper Boots",
        "Serpentscale Boots",
        "Samite Slippers",
        "Sharkskin Boots",
        "Ancient Greaves",
        "Ambush Boots",
        "Runic Sollerets",
        "Soldier Boots",
        "Darksteel Treads",
        "Nightwind Slippers",
        "Windbreak Boots",
        "Wyrmscale Boots",
        "Conjurer Boots",
        "Goliath Greaves",
        "Carnal Boots",
        "Shagreen Boots",
        "Legion Boots",
        "Hydrascale Boots",
        "Arcanist Slippers",
        "Stealth Boots",
        "Vaal Greaves",
        "Assassin's Boots",
        "Crusader Boots",
        "Dragonscale Boots",
        "Sorcerer Boots",
        "Titan Greaves",
        "Murder Boots",
        "Runic Sabatons",
        "Slink Boots",
        "Fugitive Boots",
        "Two-Toned Boots",
        "Brimstone Treads",
        "Dreamquest Slippers",
        "Stormrider Boots"
    ],
    "Belts": [
        "Stygian Vise",
        "Chain Belt",
        "Rustic Sash",
        "Heavy Belt",
        "Leather Belt",
        "Cloth Belt",
        "Micro-Distillery Belt",
        "Studded Belt",
        "Mechalarm Belt",
        "Mechanical Belt",
        "Crystal Belt",
        "Vanguard Belt"
    ],
    "Amulets": [
        "Ashscale Talisman",
        "Avian Twins Talisman",
        "Black Maw Talisman",
        "Bonespire Talisman",
        "Breakrib Talisman",
        "Clutching Talisman",
        "Deadhand Talisman",
        "Deep One Talisman",
        "Fangjaw Talisman",
        "Greatwolf Talisman",
        "Hexclaw Talisman",
        "Horned Talisman",
        "Lone Antler Talisman",
        "Longtooth Talisman",
        "Mandible Talisman",
        "Monkey Paw Talisman",
        "Monkey Twins Talisman",
        "Primal Skull Talisman",
        "Rot Head Talisman",
        "Rotfeather Talisman",
        "Spinefuse Talisman",
        "Splitnewt Talisman",
        "Three Hands Talisman",
        "Three Rat Talisman",
        "Undying Flesh Talisman",
        "Wereclaw Talisman",
        "Coral Amulet",
        "Paua Amulet",
        "Amber Amulet",
        "Jade Amulet",
        "Lapis Amulet",
        "Gold Amulet",
        "Agate Amulet",
        "Citrine Amulet",
        "Turquoise Amulet",
        "Focused Amulet",
        "Onyx Amulet",
        "Simplex Amulet",
        "Chrysalis Talisman",
        "Writhing Talisman",
        "Unset Amulet",
        "Ruby Amulet",
        "Marble Amulet",
        "Seaglass Amulet",
        "Astrolabe Amulet",
        "Blue Pearl Amulet"
    ],
    "Life Flasks": [
        "Small Life Flask",
        "Medium Life Flask",
        "Large Life Flask",
        "Greater Life Flask",
        "Grand Life Flask",
        "Giant Life Flask",
        "Colossal Life Flask",
        "Sacred Life Flask",
        "Hallowed Life Flask",
        "Sanctified Life Flask",
        "Divine Life Flask",
        "Eternal Life Flask"
    ],
    "Misc Map Items": [
        "Mirrored Tablet",
        "Chronicle of Atzoatl",
        "Inscribed Ultimatum",
        "Incandescent Invitation",
        "Polaric Invitation",
        "Screaming Invitation",
        "Writhing Invitation"
    ],
    "Quest Items": [
        "Alira's Amulet",
        "Allflame",
        "Ammonite Glyph",
        "Ankh of Eternity",
        "Atlas Book of Skill",
        "Baleful Gem",
        "Basilisk Acid",
        "Bestel's Manuscript",
        "Black Venom",
        "Bottled Storm",
        "Bust of Gaius Sentari",
        "Bust of Hector Titucius",
        "Bust of Marceus Lioneye",
        "Calendar of Fortune",
        "Chitus' Plum",
        "Contract: Antique Urn",
        "Decanter Spiritus",
        "Deshret's Banner",
        "Elixir of Allure",
        "Eye of Conquest",
        "Eyes of Zeal",
        "Firefly",
        "Flesh Compass",
        "Golden Hand",
        "Golden Page",
        "Greust's Necklace",
        "Haliotis Glyph",
        "Hinekora's Hair",
        "Infernal Talc",
        "Kishara's Star",
        "Kraityn's Amulet",
        "Luminous Astrolabe",
        "Malachai's Entrails",
        "Malachai's Heart",
        "Malachai's Lungs",
        "Maligaro's Spike",
        "Master Key",
        "Medicine Chest",
        "Miasmeter",
        "Moon Orb",
        "Oak's Amulet",
        "Obsidian Key",
        "Ribbon Spool",
        "Roseus Glyph",
        "Sekhema Feather",
        "Sewer Keys",
        "Sign of Purity",
        "Silver Locket",
        "Storm Blade",
        "Sun Orb",
        "Thaumetic Emblem",
        "Thaumetic Sulphite",
        "The Apex",
        "The Black Flag",
        "The Eye of Desire",
        "The Eye of Fury",
        "The Shaper's Key",
        "The Staff of Purity",
        "The Teardrop",
        "Tolman's Bracelet",
        "Tower Key",
        "Trarthan Powder",
        "Tukohama's Tooth",
        "Valako's Jaw",
        "Wings of Vastiri",
        "Contract: Isla's Prototypes",
        "Contract: Finding Opal",
        "Contract: Stolen Lockpicks",
        "Maligaro's Map",
        "Contract: Enoch's Whereabouts",
        "Contract: Isla's Designs",
        "Contract: Karst's Revenge",
        "Contract: Opal's Jewels",
        "Contract: The Wedding Dress",
        "Contract: A Matter of Honour",
        "Contract: Grocery List",
        "Contract: Slaver's Revenge",
        "Contract: The Admiral's Records",
        "Contract: Credit Where Credit's Due",
        "Contract: Disengagement",
        "Contract: Enoch's Remains",
        "Contract: Hyrri's Gift",
        "Contract: Rational Tools",
        "Contract: The Book of Jamanra",
        "Contract: The Nameless Play",
        "Memory Fragment",
        "Shaper's Orb",
        "Contract: A Mundane Sample",
        "Contract: Findings for Fidium",
        "Contract: Flying False Colours",
        "Contract: Follow the Paper Trail",
        "Contract: The Negotiation",
        "Contract: The Rescue",
        "Contract: The Vinderi Bomb",
        "Contract: The Finest Costumes",
        "Elder's Orb"
    ]
} as const;
